### PR TITLE
Add nfl dataset

### PR DESCRIPTION
**Pull request by geet084**
If you have found yourself wanting to go to your team's game when they are playing away from home, this app can help you to find opportunities to turn a one day trip into a mini-vacation. With different attractions for each city, you can experience that city in addition to catching your favorite team play.

### CODE REVIEW

**Comment by brittanydionigi** [comment]
@geet084 You're missing the file extension on your file name. Please add a `.js` to the end of it so it can be read appropriately.

**Comment by geet084** [comment]
@brittanystoroz I believe that I have added it now...

**Comment by brittanydionigi** [comment]
Good thank you

**Comment by geet084** [comment]
@brittanystoroz @thatPamIAm @robbiejaeger 
Please approve updated dataset with images for our fetch calls

@b3an5 @ericfitzsimons451

**Pull request merged**
